name: krang
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  shared_preferences: ^2.3.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.1
  cupertino_icons: ^1.0.8
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/logo.png
    - assets/Arrow.png
    - assets/Search.png
    - assets/icons_admin/
